spring:
  application:
    name: deblock-flights
  jackson:
    serialization:
      write-empty-json-arrays: true
server:
  port: 8080

logging:
  level:
    root: INFO

suppliers:
  timeout: 60
  crazyair:
    url: http://localhost:8095/crazyair/search
  toughjet:
    url: http://localhost:8095/toughjet/search
