spring:
  application:
    name: deblock-flights

server:
  port: 8080

logging:
  level:
    root: INFO

crazyair:
  url: http://localhost:8095/crazyair/search

toughjet:
  url: http://localhost:8095/toughjet/search
